/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcView;

import com.toedter.calendar.JDateChooser;
import javax.swing.JTable;
import javax.swing.JTextField;
import mvcController.ControllerHistory;

/**
 *
 * @author micha
 */
public class FormHistoryPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form HistoryPeminjaman
     */
    public FormHistoryPeminjaman() {
        initComponents();
        ctHistory = new ControllerHistory(this);
        ctHistory.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdAdminDiHistory = new javax.swing.JTextField();
        txtIdBukuDiHistory = new javax.swing.JTextField();
        txtJudulDiHistory = new javax.swing.JTextField();
        txtNamaPeminjam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataHistory = new javax.swing.JTable();
        btnSimpanDiHistory = new javax.swing.JButton();
        btnEditDiHistory = new javax.swing.JButton();
        btnResetDiHistory = new javax.swing.JButton();
        btnHapusDiHistory = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPencarianDiHistory = new javax.swing.JTextField();
        btnCariDiHistory = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtIdHistory = new javax.swing.JTextField();
        clndrTglPinjam = new com.toedter.calendar.JDateChooser();
        clndrTglPengembalian = new com.toedter.calendar.JDateChooser();
        btnDaftarBuku = new javax.swing.JLabel();
        btnDaftarAnggota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 28)); // NOI18N
        jLabel1.setText("History Peminjaman Buku");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID Admin");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID Buku");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Judul");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tanggal Peminjaman");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nama Peminjam");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tanggal Pengembalian");

        txtIdAdminDiHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtIdBukuDiHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtJudulDiHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNamaPeminjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNamaPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPeminjamActionPerformed(evt);
            }
        });

        tblDataHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDataHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tblDataHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataHistoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDataHistory);

        btnSimpanDiHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSimpanDiHistory.setText("Simpan");
        btnSimpanDiHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpanDiHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanDiHistoryActionPerformed(evt);
            }
        });

        btnEditDiHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditDiHistory.setText("Edit");
        btnEditDiHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditDiHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDiHistoryActionPerformed(evt);
            }
        });

        btnResetDiHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResetDiHistory.setText("Reset");
        btnResetDiHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetDiHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDiHistoryActionPerformed(evt);
            }
        });

        btnHapusDiHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHapusDiHistory.setText("Hapus");
        btnHapusDiHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusDiHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDiHistoryActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Pencarian");

        btnCariDiHistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCariDiHistory.setText("Cari");
        btnCariDiHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDiHistoryActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("ID History");

        txtIdHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDaftarBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDaftarBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open-book50.png"))); // NOI18N
        btnDaftarBuku.setText("  Daftar Buku");
        btnDaftarBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaftarBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarBukuMouseClicked(evt);
            }
        });

        btnDaftarAnggota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDaftarAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group50.png"))); // NOI18N
        btnDaftarAnggota.setText("  Daftar Anggota");
        btnDaftarAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaftarAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarAnggotaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(398, 398, 398))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDaftarAnggota)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtPencarianDiHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCariDiHistory)
                        .addGap(99, 99, 99))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 31, Short.MAX_VALUE)
                                .addComponent(btnSimpanDiHistory)
                                .addGap(27, 27, 27)
                                .addComponent(btnEditDiHistory)
                                .addGap(29, 29, 29)
                                .addComponent(btnResetDiHistory)
                                .addGap(32, 32, 32)
                                .addComponent(btnHapusDiHistory)
                                .addGap(98, 98, 98))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdAdminDiHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdBukuDiHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJudulDiHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(42, 42, 42)
                                .addComponent(clndrTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clndrTglPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnDaftarBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(clndrTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAdminDiHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(clndrTglPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdBukuDiHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJudulDiHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanDiHistory)
                    .addComponent(btnEditDiHistory)
                    .addComponent(btnResetDiHistory)
                    .addComponent(btnHapusDiHistory)
                    .addComponent(btnDaftarBuku)
                    .addComponent(btnDaftarAnggota))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtPencarianDiHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariDiHistory))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPeminjamActionPerformed

    private void btnHapusDiHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDiHistoryActionPerformed
        ctHistory.delete();
        ctHistory.isiTable();
        ctHistory.reset();
    }//GEN-LAST:event_btnHapusDiHistoryActionPerformed

    private void btnSimpanDiHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanDiHistoryActionPerformed
        ctHistory.insert();
        ctHistory.isiTable();
        ctHistory.reset();
    }//GEN-LAST:event_btnSimpanDiHistoryActionPerformed

    private void btnEditDiHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDiHistoryActionPerformed
        ctHistory.update();
        ctHistory.isiTable();
        ctHistory.reset();
    }//GEN-LAST:event_btnEditDiHistoryActionPerformed

    private void tblDataHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataHistoryMouseClicked
        int row = tblDataHistory.getSelectedRow();
        ctHistory.isiField(row);
    }//GEN-LAST:event_tblDataHistoryMouseClicked

    private void btnResetDiHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDiHistoryActionPerformed
        ctHistory.reset();
    }//GEN-LAST:event_btnResetDiHistoryActionPerformed

    private void btnCariDiHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDiHistoryActionPerformed
        ctHistory.search();
        ctHistory.reset();
    }//GEN-LAST:event_btnCariDiHistoryActionPerformed

    private void btnDaftarBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarBukuMouseClicked
        FormBuku frmBuku = new FormBuku();
        frmBuku.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDaftarBukuMouseClicked

    private void btnDaftarAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarAnggotaMouseClicked
        FormAnggota frmAnggota = new FormAnggota();
        frmAnggota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDaftarAnggotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHistoryPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHistoryPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHistoryPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHistoryPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHistoryPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariDiHistory;
    private javax.swing.JLabel btnDaftarAnggota;
    private javax.swing.JLabel btnDaftarBuku;
    private javax.swing.JButton btnEditDiHistory;
    private javax.swing.JButton btnHapusDiHistory;
    private javax.swing.JButton btnResetDiHistory;
    private javax.swing.JButton btnSimpanDiHistory;
    private com.toedter.calendar.JDateChooser clndrTglPengembalian;
    private com.toedter.calendar.JDateChooser clndrTglPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataHistory;
    private javax.swing.JTextField txtIdAdminDiHistory;
    private javax.swing.JTextField txtIdBukuDiHistory;
    private javax.swing.JTextField txtIdHistory;
    private javax.swing.JTextField txtJudulDiHistory;
    private javax.swing.JTextField txtNamaPeminjam;
    private javax.swing.JTextField txtPencarianDiHistory;
    // End of variables declaration//GEN-END:variables
    ControllerHistory ctHistory;

    public JTable getTabelData() {
        return tblDataHistory;
    }
    
    public JTextField gettxtIdHistory(){
        return txtIdHistory;
    }
    
    public JTextField gettxtIdAdmin(){
        return txtIdAdminDiHistory;
    }
    
    public JTextField gettxtIdBuku(){
        return txtIdBukuDiHistory;
    }
    
    public JTextField gettxtJudul(){
        return txtJudulDiHistory;
    }
    
    public JDateChooser gettxtTglPeminjaman(){
        return clndrTglPinjam;
    }
    
    public JTextField gettxtNamaPeminjam(){
        return txtNamaPeminjam;
    }
    
    public JDateChooser gettxtTglPengembalian(){
        return clndrTglPengembalian;
    }
    
    public JTextField gettxtCariNama(){
        return txtPencarianDiHistory;
    }
}
